[package]
name = "rust-play-ground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
opencv = "0.89.0"
serde = "1.0.197"
serde_json = "1.0.115"
